FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /raid/.tnp

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app


CMD ["python", "swa2.py"]